title: Gracious Crafts
#logo: /assets/img/headshot_circle.png
description: Your goto provider for quality Handmade Eco Bags and other handcrafted products
show_downloads: false
theme: jekyll-theme-minimal
